#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-mini_portile
Version  : 0.6.2
Release  : 5
URL      : https://rubygems.org/downloads/mini_portile-0.6.2.gem
Source0  : https://rubygems.org/downloads/mini_portile-0.6.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
= MiniPortile
* {Source Code}[https://github.com/flavorjones/mini_portile]
* {Bug Reports}[https://github.com/flavorjones/mini_portile/issues]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n mini_portile-0.6.2
gem spec %{SOURCE0} -l --ruby > rubygem-mini_portile.gemspec

%build
gem build rubygem-mini_portile.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
mini_portile-0.6.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/mini_portile-0.6.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/mini_portile-0.6.2/History.txt
/usr/lib64/ruby/gems/2.3.0/gems/mini_portile-0.6.2/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/mini_portile-0.6.2/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/mini_portile-0.6.2/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/mini_portile-0.6.2/examples/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/mini_portile-0.6.2/lib/mini_portile.rb
/usr/lib64/ruby/gems/2.3.0/specifications/mini_portile-0.6.2.gemspec
